// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCn251C1n7fU8TQ5_7z9y8rfIThcaVeHJI',
    appId: '1:833778222599:web:979e369f130d286a908ca2',
    messagingSenderId: '833778222599',
    projectId: 'tictactoe-72127',
    authDomain: 'tictactoe-72127.firebaseapp.com',
    storageBucket: 'tictactoe-72127.appspot.com',
    measurementId: 'G-PELF57WEYE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyyaMHWMUNTmoKekvZmpwT8qVJRJ97-5I',
    appId: '1:833778222599:android:58eb8a9a37baf95c908ca2',
    messagingSenderId: '833778222599',
    projectId: 'tictactoe-72127',
    storageBucket: 'tictactoe-72127.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBq3udHaJ6SapYSv41QjxeOER9QAlBisyg',
    appId: '1:833778222599:ios:d84287328982b690908ca2',
    messagingSenderId: '833778222599',
    projectId: 'tictactoe-72127',
    storageBucket: 'tictactoe-72127.appspot.com',
    iosBundleId: 'com.example.newTictacto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBq3udHaJ6SapYSv41QjxeOER9QAlBisyg',
    appId: '1:833778222599:ios:751d7508b32aecac908ca2',
    messagingSenderId: '833778222599',
    projectId: 'tictactoe-72127',
    storageBucket: 'tictactoe-72127.appspot.com',
    iosBundleId: 'com.example.newTictacto.RunnerTests',
  );
}
